#!/usr/bin/env bash

usage() { echo "Usage: $0 [-h|--help] [--run] <target-directory>" 1>&2; exit 1; }

RUN=--dry-run

while true; do
    case $1 in
        -h|--help)
            usage
            exit 0
            ;;
        --run)
            RUN=
            ;;
        *)
            break
            ;;
    esac
    shift
done

if [ -z "$1" ]; then
    usage
    exit 1
fi

rsync -avzh --info=progress2 --delete-after $RUN ~/.emacs.d "$1/"
