#!/bin/bash

DIR=$(dirname "$3")
mkdir -p "$DIR"

case "$1" in
    tgz)
        wget -O- "$2" | tar zxf - -C "$3"
        ;;
    wget)
        wget "$2" -O "$3"
        trap "rm -f $3" EXIT
        7z x -y "$3" -o"$DIR"
        ;;
    7z)
        tmp=/tmp/lsp$$
        trap "rm -f $tmp" EXIT
        wget "$2" -O "$tmp" && 7z x -y "$tmp" -o"$3"
        ;;
    py)
        tmp=/tmp/lsp$$
        trap "rm -f $tmp $3/lsp$$*" EXIT
        wget "$2" -O "$tmp" && 7z x -y "$tmp" -o"$3" && 7z x -y "$3/lsp$$*" -o"$3"
        ;;
    *)
        exit 1
esac
