# -*- mode: sh -*-

local_path=
for directory in .local .cargo .cabal .ghcup program program/root program/node program/maven; do
    if [ -d "${HOME}/${directory}/bin" ]; then
        local_path="${HOME}/${directory}/bin:${local_path}"
    fi
done

export PATH="${local_path}:${PATH}"
export LD_LIBRARY_PATH="${HOME}/.local/lib:${HOME}/.local/lib64:${LD_LIBRARY_PATH}"

alias et='emacsclient -t -a ""'
alias ec='emacsclient -c -a "" -n'
