# -*- mode: sh -*-
# Antigen: https://github.com/zsh-users/antigen
ANTIGEN="$HOME/.local/bin/antigen.zsh"

# Install antigen.zsh if not exist
if [ ! -f "$ANTIGEN" ]; then
    echo "Installing antigen ..."

    [ ! -d "$HOME/.local" ] && mkdir -p "$HOME/.local" 2> /dev/null
    [ ! -d "$HOME/.local/bin" ] && mkdir -p "$HOME/.local/bin" 2> /dev/null
    [ ! -f "$HOME/.z" ] && touch "$HOME/.z"

    URL="http://git.io/antigen"
    TMPFILE="/tmp/antigen.zsh"
    if [ -x "$(which curl)" ]; then
        curl -L "$URL" -o "$TMPFILE"
    elif [ -x "$(which wget)" ]; then
        wget "$URL" -O "$TMPFILE"
    else
        echo "ERROR: please install curl or wget before installation !!"
        exit
    fi
    if [ ! $? -eq 0 ]; then
        echo ""
        echo "ERROR: downloading antigen.zsh ($URL) failed !!"
        exit
    fi;

    echo "move $TMPFILE to $ANTIGEN"
    mv "$TMPFILE" "$ANTIGEN"
fi

# Initialize antigen
source "$ANTIGEN"

# Initialize oh-my-zsh
antigen use oh-my-zsh

antigen bundle extract
antigen bundle sudo
antigen bundle jsontools
antigen bundle zsh-users/zsh-completions

antigen theme robbyrussell

antigen apply

# Don't record an entry starting with a space.
setopt HIST_IGNORE_SPACE

export LC_CTYPE=zh_CN.UTF-8
export XMODIFIERS='@im=fcitx'
export XIM=fcitx
export XIM_PROGRAM=fcitx
export DEFAULT_USER=yyj

export EDITOR='emacsclient'
export GTAGSLABEL=ctags

export RUSTUP_DIST_SERVER=https://mirrors.tuna.tsinghua.edu.cn/rustup

export LD_LIBRARY_PATH="$HOME/program/root/lib:$LD_LIBRARY_PATH"
export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"

alias et='emacsclient -t -a ""'
alias ec='emacsclient -c -a "" -n'
alias ep='emacs --dump-file=$HOME/.emacs.d/var/emacs.pdmp'
alias root='root -l'

case "$INSIDE_EMACS" in
    vterm)
        alias ff='emacsclient -n'
        chpwd() { print -Pn '\e]51;A$(pwd)\e\\'; }
        # cd() {
        #     builtin cd "$@" || return;
        #     [ "$OLDPWD" = "$PWD" ] || echo -ne "\e]51;A$(pwd)\e\\";
        # };
        ;;
    *term*)
        alias ff='emacsclient -n'
        chpwd() {
            printf '\033AnSiTu %s\n' "$USER"
            print -P '\033AnSiTc %d'
        }
        ;;
    *)
        alias ff='emacsclient -c -a "" -n'
        # Enable 256 color to make auto-suggestions look nice
        export TERM="xterm-256color"
        ;;
esac
