# -*- mode: sh -*-

ANTIGEN="$HOME/.antigen/antigen.zsh"

# Install antigen.zsh if not exist
if [ ! -f "$ANTIGEN" ]; then
    echo "Installing antigen ..."

    [ ! -d "$HOME/.local" ] && mkdir -p "$HOME/.local" 2> /dev/null
    [ ! -d "$HOME/.local/bin" ] && mkdir -p "$HOME/.local/bin" 2> /dev/null
    [ ! -f "$HOME/.z" ] && touch "$HOME/.z"

    URL="http://git.io/antigen"
    TMPFILE="/tmp/antigen.zsh.$$"

    trap "rm -f $TMPFILE" EXIT

    if [ -x "$(which curl)" ]; then
        curl -L "$URL" -o "$TMPFILE"
    elif [ -x "$(which wget)" ]; then
        wget "$URL" -O "$TMPFILE"
    else
        echo "ERROR: please install curl or wget before installation !!"
        exit 1
    fi
    if [ ! $? -eq 0 ]; then
        echo "ERROR: downloading antigen.zsh ($URL) failed !!"
        exit 1
    fi;

    echo "move $TMPFILE to $ANTIGEN"
    mv "$TMPFILE" "$ANTIGEN"
fi

# Initialize antigen
source "$ANTIGEN"

antigen use oh-my-zsh

antigen bundle extract
antigen bundle jsontools
antigen bundle zsh-users/zsh-completions

antigen theme robbyrussell

antigen apply

# Don't record an entry starting with a space.
setopt HIST_IGNORE_SPACE

typeset -U path

export AGKOZAK_LEFT_PROMPT_ONLY=1

export LC_CTYPE=zh_CN.UTF-8
export XMODIFIERS='@im=fcitx'
export XIM=fcitx
export XIM_PROGRAM=fcitx
export DEFAULT_USER=yyj

export EDITOR='emacsclient'
export GTAGSLABEL=ctags

export RUSTUP_DIST_SERVER=https://mirrors.tuna.tsinghua.edu.cn/rustup

if [ "$(uname -s)" = "Linux" ]; then
    export FZF_DEFAULT_COMMAND='fdfind --type=file'
else
    export FZF_DEFAULT_COMMAND='fd --type=file'
fi

for directory in ".local" ".cargo" ".cabal" ".ghcup" "program/root" "program/node";do
    if [ -d "$HOME/${directory}/bin" ]; then
        path=("$HOME/${directory}/bin" "$path[@]")
    fi
done

if [ -x "$HOME/.zshrc.local" ]; then
    . "$HOME/.zshrc.local"
fi

alias et='emacsclient -t -a ""'
alias ec='emacsclient -c -a "" -n'
alias ep='emacs --dump-file=$HOME/.emacs.d/.cache/emacs.pdmp'
alias gnus='emacs --eval "(gnus)"'

hash -d e=$HOME/.emacs.d
hash -d d=$HOME/downloads
hash -d w=$HOME/working

case "$INSIDE_EMACS" in
    vterm)
        alias ff='emacsclient -n'
        chpwd() { print -Pn '\e]51;A$(pwd)\e\\'; }
        # cd() {
        #     builtin cd "$@" || return;
        #     [ "$OLDPWD" = "$PWD" ] || echo -ne "\e]51;A$(pwd)\e\\";
        # };
        ;;
    *term*)
        alias ff='emacsclient -n'
        chpwd() {
            printf '\033AnSiTu %s\n' "$USER"
            print -P '\033AnSiTc %d'
        }
        ;;
    *)
        alias ff='emacsclient -c -a "" -n'
        ;;
esac
